// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEQO5fLVjkA12xf9mWpMWmvzFppwNlAk0',
    appId: '1:314258669064:web:92121ef9bbb4fbfaf09bbd',
    messagingSenderId: '314258669064',
    projectId: 'project-manager-95a48',
    authDomain: 'project-manager-95a48.firebaseapp.com',
    storageBucket: 'project-manager-95a48.firebasestorage.app',
    measurementId: 'G-WWXY3V97GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRiGPNbUK_3_DSYK2N7TP33RrsxjiztHg',
    appId: '1:314258669064:android:5836c4f73ea15a37f09bbd',
    messagingSenderId: '314258669064',
    projectId: 'project-manager-95a48',
    storageBucket: 'project-manager-95a48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Czr6B2W21JctYFJ1f61ac_3w3H9qpok',
    appId: '1:314258669064:ios:e49d5e9690b3cd8ff09bbd',
    messagingSenderId: '314258669064',
    projectId: 'project-manager-95a48',
    storageBucket: 'project-manager-95a48.firebasestorage.app',
    iosBundleId: 'com.example.projectManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Czr6B2W21JctYFJ1f61ac_3w3H9qpok',
    appId: '1:314258669064:ios:e49d5e9690b3cd8ff09bbd',
    messagingSenderId: '314258669064',
    projectId: 'project-manager-95a48',
    storageBucket: 'project-manager-95a48.firebasestorage.app',
    iosBundleId: 'com.example.projectManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEQO5fLVjkA12xf9mWpMWmvzFppwNlAk0',
    appId: '1:314258669064:web:7640a0692c0b15aff09bbd',
    messagingSenderId: '314258669064',
    projectId: 'project-manager-95a48',
    authDomain: 'project-manager-95a48.firebaseapp.com',
    storageBucket: 'project-manager-95a48.firebasestorage.app',
    measurementId: 'G-4PC0LJ33NP',
  );

}